---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "0 18 * * *"

jobs:
  build:
    name: ci
    uses: openrewrite/gh-automation/.github/workflows/ci-gradle-standard.yml@main
    secrets:
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_token: ${{ secrets.OSSRH_TOKEN }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      gradle_enterprise_access_key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
