---
name: Moderne ingest

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  schedule:
    - cron: "0 18 * * *"

jobs:
  ingest:
    uses: openrewrite/gh-automation/.github/workflows/moderne-ingest.yml@main
    secrets:
      moderne_api_access_token: ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
